# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

name: Evan G Giese
title: Software Developer
email: evangiese77@gmail.com
#phone: Your phone number (optional)
#website: evangiese.tk

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: evangiese
github_username: evangee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: evan-giese-47192bba
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  *programmer joke: __!false__, it’s funny because it’s true.*

  At university I was one of the founders and vice president of the MacEwan computer science club. As vice president, I helped 
  students get engaged in computer science, raising the club membership from around 10 to over 100 people in a couple months. My
  involvement encouraged other club members to put in 100% effort, and together we organized many talks and events. Today, the club still exists with over 600 members online. 

  I volunteer at the University of Alberta helping the Alberta Sat team build a satellite. In addition to writing and integrating a file transfer protocol, 
  I help design and integrate drivers, design software, and analyse potential opensource alternatives. My work is helping the software team 
  achieve their goals of building an opensource satellite platform.

  As a member of Google ignite (google), I designed lessons for high school students, teaching them about computer networking. The students
  got to build and deploy their own websites.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        name: Open Ethereum Wallet
        link: https://evangiese.tk/open-ethereum-wallet/
        github: https://github.com/EvanGee/OpenEthereumWallet
        quote: >
          Open Ethereum Wallet is a wallet app that lets you store keys and easily interact with smart contracts.

        description: | # this will include new lines to allow paragraphs
          Open Ethereum Wallet is a wallet app that lets users easily interact with a 
          variety of block-chain applications using a simple rest API. It has a mobile app GUI, but can operate without a GUI.

        # Project template
      - layout: top-middle
        name: multi-level feedback queue (MLFQ) simulation
        link: https://learn-mlfq.herokuapp.com/
        quote: >
          This is a simulation of a multilevel feedback queue.
        description: | # this will include new lines to allow paragraphs
          This project was built to aid students in learning how a MLFQ functions. We wrote a paper on it which is published in 
          '2017 8th IEEE Annual Information Technology, Electronics and Mobile Communication Conference (IEMCON)' you can read it here
          https://ieeexplore.ieee.org/document/8117201

        # Project template
      - layout: top-middle
        name: The Consultative Committee for Space Data Systems (CCSDS) File delivery protocol
        github: https://github.com/EvanGee/CCSDS_FileDeliveryProtocol
        quote: >
          This is a file transfer protocol written in C that adheres to CCSDS standards
        description: | # this will include new lines to allow paragraphs
          This project is still being worked on, it adheres to strict space design standards for file transfer. We are planning to add it to the opensource satellite project at the Universtiy of Alberta.

        # Project template
      - layout: top-middle
        name: My Blog!
        description: | # this will include new lines to allow paragraphs
          I have lots of project's i'm always working on, If I were to put them all on my resume, It would be too bloated. Check it out at evangiese.tk

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # Experience template
      - layout: left
        company: Private photography company
        #link: Link to company (optional)
        job_title: Software contractor
        dates: August 2018 - September 2018
        quote: >
          a small photography company, that wanted an app built to rename photos
          description: | # this will include new lines to allow paragraphs
          As a contractor, I helped deliver value to their organization by reducing costs. This app
          reduces the time employees need to label and download images for portfolios by approximately 20 minutes a day.
          You can check it out a simple version here https://evangee.github.io/ImageOrganizer/#/

      - layout: left
        company: Dell EMC/HCL
        #link: Link to company (optional)
        job_title: Senior Software Engineer(U.S)
        dates: Oct 10 2019 - present
        quote: >
          Building cool stuff for data centers
          description: | # this will include new lines to allow paragraphs
          As a software engineer (U.S) I help to diagnose bugs in Dell's product firmware, as well as other potential bugs that customers
          face. Dell relies on my knowledge of storage area networks to provide support to customers who have unforsean issues with their products.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        name: MacEwan University
        dates: 2016 - 2019
        qualification: Bachelor of Science
        quote: >
          Major in computer science with a minor in economics
        description: | # this will include new lines to allow paragraphs
          Developed an understanding of common programming languages (java, C#, python, sql, etc), with extra focus on C. Developed understanding
          of networks, operating systems, security, databases, agile development and working in teams, and more.
      - layout: left
        name: MacEwan University
        dates: 2012 - 2016
        qualification: Bachelor of Commerce
        quote: >
          Major in Accounting with a focus in finance
        description: | # this will include new lines to allow paragraphs
          Developed an understanding of corporate financial structures, and impactful business decisions. 
          The importance of the triple bottom line, communication, and how to work in teams. We did an immense amount of group work.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
