# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

name: Evan G Giese
title: Software Engineer
email: evangiese77@gmail.com
#phone: Your phone number (optional)
#website: evangiese.tk

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: evangiese
github_username: evangee
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: evan-giese-47192bba
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#  - title: itsgoingto.be
#    icon: fas fa-globe
#    url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/new_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  *programmer joke: __!false__, it’s funny because it’s true.*

  As the first software engineer at Wyvern, I had the opportunity to design and integrate the CI/CD pipeline, web technologies and 
  frameworks, custom ETL pipelines, and cloud infrastructure. My software allowed us to qualify for an NRC IRAP grant which financed the 
  software development for 2 years.  I was able to gain a lot of experience in a short amount of time, using industry standard tools like Git, Terraform, ARGO (kubernetes), AWS ECS, and much more. I am proficient in Python, Javascript, 
  Typescript, React, React-native, Golang, Java, and C for development purposes. In addition to development, I was able to help create a culture of learning, 
  kindness, and growth at Wyvern.
  
  At University I was one of the founders and the vice president of the MacEwan computer science club. As vice president, I helped
  students engage in computer science through teaching, club activities, and organizing events.
  A favorite memory of mine is teaching a fellow student about HEX (base 16), and having it finally click for them.
  My contribution raised the club membership from around 10 to over 100 people in a couple months.
  Today, the club still exists and has grown to thousands of computer science students and Alumni.
  
content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      # Experience template
      - layout: top-middle
        title: Wyvern
        #link: Link to company (optional)
        sub_title: Software Engineer
        caption: August 2021 - present
        quote: >
          Designing and integrating order automation, orbit prediction, scalable cloud solutions, and internal web applications.
        description: | # this will include new lines to allow paragraphs
          I was the seventh employee and first software person on the team. They rely on me to figure out when and where to take photo's from space, and construct a scalable, secure, extensible software stack
          that can be used to process customer orders and task our now 3 active satellites in commerical operations. My main contributions were:
            - designing and implementing an event driven architecture using Golang and Kafka that allows for easy integration of new microservices. 
            This gave the team a framework for building microservices, which saved time and mental energy when implementing services. 
            - I built an orbital prediction microservice using opensource technology, which was much cheeper than the industry leading software (which costs around 80k/year). 
            - I built a satellite tasking application using React and Django that we use internally to schedule satellite assets, and
            is currently being used to schedule our commercial opperations. 
            - Developing the software portion of our remote space sensing license application (RSSSA) to ensure that our software was compliant 
            with government security standards.

      - layout: top-middle
        title: Dell EMC/HCL
        #link: Link to company (optional)
        sub_title: Senior Software Engineer
        caption: October 2019 - August 2021
        quote: >
          Building cool stuff for data centers
        description: | # this will include new lines to allow paragraphs
          As a software engineer (U.S) I helped to diagnose bugs in Dell's product firmware. Dell relied on my knowledge of storage area networks
          to provide support to customers who have unforeseen issues with their products. I helped saved banks and other large customers millions
          of dollars from data center outages.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: MacEwan University
        sub_title: Bachelor of Science
        caption: 2016 - 2019
        quote: >
          Major in computer science with a minor in economics.
        description: | # this will include new lines to allow paragraphs
          Developed an understanding of many common programming languages (java, C#, python, sql, Go, C etc), with extra focus on C. 
          Developed understanding of networks, operating systems, security, databases, agile development, working in teams, and more.

      - layout: top-middle
        title: MacEwan University
        sub_title: Bachelor of Commerce
        caption: 2012 - 2016
        quote: >
          Major in Accounting with a focus in finance.
        description: | # this will include new lines to allow paragraphs
          Developed an understanding of corporate financial structures, and impactful business decisions. My favorite classes were
          tax, law, finance, and banking.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: top-middle
        title: Weatherfurcast.com
        quote: >
          A weather forcast app that uses AI models of pets.
        description: | # this will include new lines to allow paragraphs
          This project was built to display weather updates in a fun way. The app display changes in weather by displaying cute pictures of pets that change based on the weather. Mobile App is pending google approval.

      # Project template
      - layout: top-middle
        title: multi-level feedback queue (MLFQ) simulation
        quote: >
          This is a simulation of a multilevel feedback queue.
        description: | # this will include new lines to allow paragraphs
          This project was built to aid students in learning how an MLFQ functions. We wrote a paper on it which is published in 
          '2017 8th IEEE Annual Information Technology, Electronics and Mobile Communication Conference (IEMCON).' Click on the above link to read it.
        link: https://ieeexplore.ieee.org/document/8117201

        # Project template
      - layout: top-middle
        title: The Consultative Committee for Space Data Systems (CCSDS) File delivery protocol
        quote: >
          This is a file transfer protocol written in C that adheres to CCSDS standards.
        description: | # this will include new lines to allow paragraphs
          This project adheres to strict space design standards for file transfer. We use a version of it on Ex-alta-2,
          the open-source satellite project at the University of Alberta, which is currently in space.
        link: https://github.com/EvanGee/CCSDS_FileDeliveryProtocol

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - I love trying to save people money. I have a passion for financial literacy.
      - Economics and banking. I use graphana to congregate and track specific financial market data.
      - Getting more involved in the edmonton dev community. I've been attending meetups, but want to try and present at one soon.

      Here is my home made, fully automated, High Pressure Aeroponics setup in my house. It uses 95% less water usuage and 60% less fertilizer than traditional hydroponics. 

      ![Plants1](/EvanGee/images/plants1.jpg "Plants1")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
